In [1]:
import math
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
from IPython.display import display
import pprint 
pp = pprint.PrettyPrinter(indent = 2)

# Config the matlotlib backend as plotting inline in IPython
%matplotlib inline

In [2]:
data = pd.read_hdf('banking.h5', 'data')
target = "y"
display(data.head(10))

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
0,44,blue-collar,married,basic.4y,unknown,yes,no,cellular,aug,thu,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.963,5228.1,0
1,53,technician,married,unknown,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,0
2,28,management,single,university.degree,no,yes,no,cellular,jun,thu,...,3,6,2,success,-1.7,94.055,-39.8,0.729,4991.6,1
3,39,services,married,high.school,no,no,no,cellular,apr,fri,...,2,999,0,nonexistent,-1.8,93.075,-47.1,1.405,5099.1,0
4,55,retired,married,basic.4y,no,yes,no,cellular,aug,fri,...,1,3,1,success,-2.9,92.201,-31.4,0.869,5076.2,1
5,30,management,divorced,basic.4y,no,yes,no,cellular,jul,tue,...,8,999,0,nonexistent,1.4,93.918,-42.7,4.961,5228.1,0
6,37,blue-collar,married,basic.4y,no,yes,no,cellular,may,thu,...,1,999,0,nonexistent,-1.8,92.893,-46.2,1.327,5099.1,0
7,39,blue-collar,divorced,basic.9y,no,yes,no,cellular,may,fri,...,1,999,0,nonexistent,-1.8,92.893,-46.2,1.313,5099.1,0
8,36,admin.,married,university.degree,no,no,no,cellular,jun,mon,...,1,3,1,success,-2.9,92.963,-40.8,1.266,5076.2,1
9,27,blue-collar,single,basic.4y,no,yes,no,cellular,apr,thu,...,2,999,1,failure,-1.8,93.075,-47.1,1.410,5099.1,0

In [3]:
from Scoring_tools import calculate_woe, woe_table_to_dict

df_woe = calculate_woe(data, "job", target)
display(df_woe)

woe_dict = woe_table_to_dict(df_woe)
pp.pprint(woe_dict)

,Column_Name,Category,Count,Events,Bad_Rate,Non-Events,Event_Distribution,Non-Event_Distribution,WoE,IV
0,job,student,875,275,0.314286,600,0.059267,0.016417,-1.283754,5.500945e-02
1,job,retired,1720,434,0.252326,1286,0.093534,0.035187,-0.977665,5.704466e-02
2,job,unemployed,1014,144,0.142012,870,0.031034,0.023804,-0.265232,1.917674e-03
3,job,admin.,10422,1352,0.129726,9070,0.291379,0.248167,-0.160525,6.936681e-03
4,job,management,2924,328,0.112175,2596,0.070690,0.071030,0.004801,1.633538e-06
5,job,unknown,330,37,0.112121,293,0.007974,0.008017,0.005343,2.282177e-07
6,job,technician,6743,730,0.108260,6013,0.157328,0.164523,0.044722,3.218128e-04
7,job,self-employed,1421,149,0.104856,1272,0.032112,0.034804,0.080487,2.166298e-04
8,job,housemaid,1060,106,0.100000,954,0.022845,0.026103,0.133312,4.343096e-04
9,job,entrepreneur,1456,124,0.085165,1332,0.026724,0.036445,0.310243,3.015900e-03
10,job,services,3969,323,0.081381,3646,0.069612,0.099759,0.359822,1.084759e-02
11,job,blue-collar,9254,638,0.068943,8616,0.137500,0.235745,0.539126,5.296630e-02

{ 'admin.': -0.16052481239193747,
  'blue-collar': 0.5391258365932243,
  'entrepreneur': 0.3102431865970874,
  'housemaid': 0.13331247843800917,
  'management': 0.004801370541626522,
  'retired': -0.9776647282010504,
  'self-employed': 0.080487339056398,
  'services': 0.3598215331177416,
  'student': -1.2837535413486352,
  'technician': 0.044722437998921664,
  'unemployed': -0.2652321868255814,
  'unknown': 0.005342597474632559}

In [4]:
df_woe = calculate_woe(data, "pdays", target)
display(df_woe)

,Column_Name,Category,Count,Events,Bad_Rate,Non-Events,Event_Distribution,Non-Event_Distribution,WoE,IV
0,pdays,27,1,1,1.000000,0,0.000216,2.736128e-07,-6.669082,0.001435
1,pdays,26,1,1,1.000000,0,0.000216,2.736128e-07,-6.669082,0.001435
2,pdays,25,1,1,1.000000,0,0.000216,2.736128e-07,-6.669082,0.001435
3,pdays,21,2,2,1.000000,0,0.000431,2.736128e-07,-7.362229,0.003171
4,pdays,13,36,28,0.777778,8,0.006034,2.188902e-04,-3.316675,0.019288
5,pdays,6,412,289,0.701456,123,0.062284,3.365437e-03,-2.918154,0.171935
6,pdays,3,439,298,0.678815,141,0.064224,3.857940e-03,-2.812246,0.169765
7,pdays,15,24,16,0.666667,8,0.003448,2.188902e-04,-2.757059,0.008904
8,pdays,22,3,2,0.666667,1,0.000431,2.736128e-05,-2.757059,0.001113
9,pdays,0,15,10,0.666667,5,0.002155,1.368064e-04,-2.757059,0.005565
10,pdays,8,18,12,0.666667,6,0.002586,1.641677e-04,-2.757059,0.006678
11,pdays,7,60,40,0.666667,20,0.008621,5.472256e-04,-2.757059,0.022259
12,pdays,5,46,29,0.630435,17,0.006250,4.651417e-04,-2.597995,0.015029
13,pdays,2,61,37,0.606557,24,0.007974,6.566707e-04,-2.496776,0.018270
14,pdays,10,52,30,0.576923,22,0.006466,6.019481e-04,-2.374067,0.013921
15,pdays,18,7,4,0.571429,3,0.000862,8.208383e-05,-2.351594,0.001834
16,pdays,14,20,11,0.550000,9,0.002371,2.462515e-04,-2.264583,0.004811
17,pdays,9,64,35,0.546875,29,0.007543,7.934771e-04,-2.251964,0.015200
18,pdays,16,11,6,0.545455,5,0.001293,1.368064e-04,-2.246234,0.002597
19,pdays,11,28,15,0.535714,13,0.003233,3.556966e-04,-2.207013,0.006350
20,pdays,4,118,63,0.533898,55,0.013578,1.504870e-03,-2.199714,0.026557
21,pdays,12,58,26,0.448276,32,0.005603,8.755609e-04,-1.856273,0.008776
22,pdays,19,3,1,0.333333,2,0.000216,5.472256e-05,-1.370765,0.000220
23,pdays,1,26,8,0.307692,18,0.001724,4.925030e-04,-1.252982,0.001543
24,pdays,17,8,2,0.250000,6,0.000431,1.641677e-04,-0.965300,0.000258
25,pdays,999,39673,3673,0.092582,36000,0.791595,9.850060e-01,0.218598,0.042279
26,pdays,20,1,0,0.000000,1,0.000002,2.736128e-05,2.541258,0.000064